export const mockUsers = [
  {
    id: "1",
    name: "Demo User",
    email: "demo@swasthwrap.com",
    password: "demo123",
    language: "en",
    interests: ["diabetes", "heart"],
    healthScore: 85,
    streak: 10,
    upcomingAppointments: 2,
    medicationsDue: 1,
  },
  {
    id: "2",
    name: "Alice Smith",
    email: "alice@example.com",
    password: "password123",
    language: "en",
    interests: ["nutrition", "fitness"],
    healthScore: 78,
    streak: 5,
    upcomingAppointments: 0,
    medicationsDue: 0,
  },
  {
    id: "3",
    name: "Bob Johnson",
    email: "bob@example.com",
    password: "securepass",
    language: "hi",
    interests: ["mental", "sleep"],
    healthScore: 92,
    streak: 20,
    upcomingAppointments: 1,
    medicationsDue: 0,
  },
]
